export const FETCH_STARTED = 'ADDR/FETCH_STARTED'
export const FETCH_SUCCESS = 'ADDR/FETCH_SUCCESS'
export const FETCH_FAILURE = 'ADDR/FETCH_FAILURE'
export const DELETE_ADDR = 'ADDR/DELETE_ADDR'
export const SELECT_ADDR = 'ADDR/SELECT_ADDR'
export const ADD_ADDR = 'ADDR/ADD_ADDR'

